- id: oops-addons-table
  name: Generate addons table in README
  always_run: true
  entry: oops-addons-table
  language: python
  pass_filenames: false

- id: oops-man-fix
  name: Fix the manifest
  entry: oops-man-fix
  pass_filenames: false
  language: python
  files: (__manifest__\.py|__openerp__\.py|__terp__\.py)$
