- id: update-readme
  name: Update README (addons table)
  entry: oops-readme-update
  language: python
  pass_filenames: false

- id: exclude-addons
  name: Exclude addons from pre-commit checks
  entry: oops-pro-exclude
  language: python
  pass_filenames: false

- id: check-project
  name: Check project configuration
  entry: oops-pro-check
  language: python
  pass_filenames: false

- id: check-manifest
  name: Check manifest files
  entry: oops-man-check
  language: python
  types: [python]
  pass_filenames: true
  files: (__manifest__\.py|__openerp__\.py|__terp__\.py)$

- id: check-submodules
  name: Check submodules
  entry: oops-sub-check
  language: python
  pass_filenames: false
