site_name: Oops
site_description: CLI toolkit for managing Odoo multi-repository projects
site_author: Apik
repo_url: https://github.com/apikcloud/oops
repo_name: apikcloud/oops

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: custom
      accent: customs
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - toc.follow

extra:
  version:
    provider: mike
    default: latest
    alias: true

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - mkdocs-click
  - admonition # Callout blocks (note, tip, warning...)
  - pymdownx.details # Collapsible callout blocks
  - pymdownx.superfences: # Advanced code blocks
      custom_fences:
        - name: mermaid # Mermaid diagrams
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # Content tabs
      alternate_style: true
  - pymdownx.highlight: # Syntax highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # Inline code highlighting
  - pymdownx.snippets # File inclusion
  - pymdownx.emoji: # Emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list # HTML attributes on elements
  - md_in_html # Markdown inside HTML
  - tables # Tables
  - footnotes # Footnotes
  - pymdownx.critic # Change tracking
  - pymdownx.caret # Superscript and insertion
  - pymdownx.keys # Keyboard shortcuts
  - pymdownx.mark # Text highlighting
  - pymdownx.tilde # Subscript and strikethrough
  - toc: # Table of contents
      permalink: true
  - pymdownx.tasklist: # Task lists
      custom_checkbox: true
  - def_list # Definition lists
  - abbr # Abbreviations

nav:
  - Home: index.md
  - Commands:
      - Addons: commands/addons.md
      - Project: commands/project.md
      - Readme: commands/readme.md
      - Submodules: commands/submodules.md
  - Hooks: hooks.md
  - Configuration: config.md
  - Use case: use-case.md
  - Contributing: contributing.md
