site_name: Oops
site_description: CLI toolkit for managing Odoo multi-repository projects
site_author: Apik
repo_url: https://github.com/apikcloud/oops
repo_name: apikcloud/oops

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: custom
      accent: customs
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - toc.follow

extra:
  version:
    provider: mike
    default: latest
    alias: true

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          # Load object inventories to enable cross-references to other projects.
          inventories:
            - https://docs.python.org/3/objects.inv
          # Also load inventories of your dependencies, generally served at
          # https://docs-url-for-your-dependency/objects.inv.

          options:
            # DOCSTRINGS -------------------------------------------------------------
            docstring_options:
              # Discard first line of `__init__` method docstrings,
              # useful when merging such docstrings into their parent class'.
              ignore_init_summary: true

            # Tables are generally too large, lists will fix this.
            docstring_section_style: table

            # CROSS-REFERENCES -------------------------------------------------------
            # Enable relative crossrefs and scoped crossrefs, see Docstrings options.
            relative_crossrefs: true # Sponsors only!
            scoped_crossrefs: true # Sponsors only!

            # Enable cross-references in signatures.
            signature_crossrefs: true

            # Unwrap actual types from `Annotated` type annotations.
            unwrap_annotated: true

            # MEMBERS ----------------------------------------------------------------
            # Only render pulic symbols.
            filters: public # Sponsors only!
            # Comment the option otherwise to get the default filters.

            # Show class inherited members.
            inherited_members: true

            # Render auto-generated summaries of attributes, functions, etc.
            # at the start of each symbol's documentation.
            summary: true

            # HEADINGS ---------------------------------------------------------------
            # For auto-generated pages, one module per page,
            # make the module heading be the H1 heading of the page.
            heading_level: 2

            # Render headings for parameters, making them linkable.
            parameter_headings: true

            # Render headings for type parameters too.
            type_parameter_headings: true

            # Always show the heading for the symbol you render with `::: id`.
            show_root_heading: true

            # Only show the name of the symbols you inject render `::: id`.
            show_root_full_path: false

            # Show the type of symbol (class, function, etc.) in the heading.
            show_symbol_type_heading: true

            # Show the type of symbol (class, function, etc.) in the table of contents.
            show_symbol_type_toc: true

            # SIGNATURES -------------------------------------------------------------
            # Format code to 80 + 10% margin (Black and Ruff defaults)
            # in signatures and attribute value code blocks.
            # Needs Black/Ruff installed.
            line_length: 88

            # Merge signature and docstring of `__init__` methods
            # into their parent class signature and docstring.
            merge_init_into_class: true

            # Render signatures and attribute values in a separate code block,
            # below the symbol heading.
            separate_signature: true

            # Show type annotations in signatures.
            show_signature_annotations: true

            # Show type parameters in signatures.
            show_signature_type_parameters: true

            # OTHER ------------------------------------------------------------------
            # Show backlinks to other documentation sections within each symbol.
            backlinks: tree # Sponsors only!

            # Show base classes OR inheritance diagram.
            show_bases: false
            show_inheritance_diagram: true # Sponsors only!

markdown_extensions:
  - mkdocs-click
  - admonition # Callout blocks (note, tip, warning...)
  - pymdownx.details # Collapsible callout blocks
  - pymdownx.superfences: # Advanced code blocks
      custom_fences:
        - name: mermaid # Mermaid diagrams
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # Content tabs
      alternate_style: true
  - pymdownx.highlight: # Syntax highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # Inline code highlighting
  - pymdownx.snippets # File inclusion
  - pymdownx.emoji: # Emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list # HTML attributes on elements
  - md_in_html # Markdown inside HTML
  - tables # Tables
  - footnotes # Footnotes
  - pymdownx.critic # Change tracking
  - pymdownx.caret # Superscript and insertion
  - pymdownx.keys # Keyboard shortcuts
  - pymdownx.mark # Text highlighting
  - pymdownx.tilde # Subscript and strikethrough
  - toc: # Table of contents
      permalink: true
  - pymdownx.tasklist: # Task lists
      custom_checkbox: true
  - def_list # Definition lists
  - abbr # Abbreviations

nav:
  - Home: index.md
  - Commands:
      - Addons: commands/addons.md
      - Manifest: commands/manifest.md
      - Odoo: commands/odoo.md
      - Project: commands/project.md
      - Readme: commands/readme.md
      - Release: commands/release.md
      - Submodules: commands/submodules.md
  - Hooks: hooks.md
  - Lint Rules: rules.md
  - Configuration: config.md
  - Use case: use-case.md
  - Contributing: contributing.md
  - Reference:
      - Core:
          - Config: reference/core/config.md
          - Exceptions: reference/core/exceptions.md
          - Messages: reference/core/messages.md
          - Models: reference/core/models.md
          - Paths: reference/core/paths.md
      - IO:
          - File: reference/io/file.md
          - Manifest: reference/io/manifest.md
          - Tools: reference/io/tools.md
      - Services:
          - Docker: reference/services/docker.md
          - Git: reference/services/git.md
          - GitHub: reference/services/github.md
      - Utils:
          - Helpers: reference/utils/helpers.md
          - Net: reference/utils/net.md
          - Render: reference/utils/render.md
          - Versioning: reference/utils/versioning.md
      - Rules:
          - Manifest: reference/rules/manifest.md
