# Copyright 2026 apik (https://apik.cloud).
# License AGPL-3.0-only (https://www.gnu.org/licenses/agpl-3.0.html)

"""
Strip every non-core addon (custom, OCA, third-party) from the project,
bump the project to the target Odoo version, sync project scaffolding, and
replace the stripped addons with an upgrade-util script that uninstalls the
same modules from the database, in reverse Odoo registry load order,
*before* the base module itself is upgraded (Odoo's `--pre-upgrade-scripts`
mechanism — the recommended context for module removal/rename/merge
operations, since once `base` is upgraded the module-state bookkeeping the
upgrade process relies on is expected to already be settled).

This is the "vanilla" starting point: a branch on the target Odoo
version, stripped down to pure core, used as the base for every MdV
(montee de version) project. Independent of state.yml/plan.yml — no
per-module porting decisions apply here, everything non-core is removed.
"""

from __future__ import annotations

import os
import re
import tempfile
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import click
import requests
import yaml
from git import Repo
from oops.commands.base import command, render_and_exit
from oops.core.config import config
from oops.core.exceptions import APIError, OopsError
from oops.core.logger import live_progress, log
from oops.core.metadata import get_metadata
from oops.core.models import Plan, PlanAction, Result
from oops.io.file import parse_odoo_version, parse_packages, write_text_file
from oops.io.installed_modules import read_installed_modules
from oops.output.formatters import FormatterRegistry, JsonFormatter, OutputFormatter, SimpleSummaryConsoleFormatter
from oops.output.workflow import run_mutation_workflow
from oops.services.docker import find_available_images
from oops.services.git import commit_v2, list_submodules, require_repository
from oops.services.kb import load_odoo_kb
from oops.services.project import copy_project_files, fetch_project_files
from oops.services.submodule import remove_submodule
from oops.utils.render import warn_experimental, warning_section
from oops_engine.addons import discover_addons
from oops_engine.build import compute_root_drift
from oops_engine.compat import Optional
from oops_engine.load_order import compute_load_order
from oops_engine.models import Addon
from oops_engine.provenance import normalize_origin

from .common import ARTIFACT_DIR, artifact_path
from .presenters.vanilla import VanillaPresenter

UTC = timezone.utc

FORMATTERS: FormatterRegistry = {
    "text": SimpleSummaryConsoleFormatter,
    "json": JsonFormatter,
}

UPGRADE_UTIL_REQUIREMENT = "odoo_upgrade @ git+https://github.com/odoo/upgrade-util@master"

VANILLA_REPORT_FILE = ARTIFACT_DIR / "vanilla.yml"
# At the root of the upgrade folder, not nested under <module>/migrations/<version>/
# — a --pre-upgrade-scripts file is referenced by explicit path, not auto-discovered
# by directory convention, so it has no module/version home of its own.
SCRIPT_REL_PATH = Path("upgrade") / "pre-uninstall_non_core_modules.py"

UNINSTALL_SCRIPT_TEMPLATE = """\
# Auto-generated by `oops upgrade vanilla` on {generated_at}.
# Do not edit by hand — regenerate with `oops upgrade vanilla`.
#
# Uninstalls every non-core module still present in the database, in
# reverse Odoo registry load order (last-loaded first), to return the
# database to a pure Odoo-standard state.
#
# This is a --pre-upgrade-scripts file (Odoo >= 16), NOT a standard
# <module>/migrations/<version>/*.py script — it is not auto-discovered.
# Wire it into the actual upgrade run explicitly:
#
#   ./odoo-bin -u all --pre-upgrade-scripts={script_path} ...
#
# It runs once, before the `base` module itself is loaded/upgraded — the
# module-removal operations below rely on the OLD (pre-upgrade) module
# bookkeeping still being in place, which is exactly why this must run
# before base, not after (see the "Phases of upgrade scripts" section at
# the doc link below). `version` is base's currently-installed (old)
# version, not a target version. The `module_installed` guard is kept for
# safety in case the upgrade run is retried, though this script is invoked
# per-run rather than auto-triggered on every future boot.
#
# See: https://www.odoo.com/documentation/master/developer/reference/upgrades/upgrade_scripts.html

import sys

from odoo.upgrade import util
from odoo.upgrade.util import helpers as util_helpers

# _name without a full stop: accepted by the ORM, rejected by the util heuristic.
DOTLESS_MODELS = {{
    {dotless_models}
}}

_original_validate_model = util_helpers._validate_model

# (module_name, load_index) — load_index is the module's position in the
# forward Odoo registry load order; modules are removed highest-first.
MODULES = [
{module_lines}
]

def _patched_validate_model(model):
    if model in DOTLESS_MODELS:
        return
    _original_validate_model(model)


def _allow_dotless_models():
    # models.py contains `from .helpers import _validate_model`: patch helpers
    # This alone is not enough; you need to update every submodule in util.
    for name, mod in list(sys.modules.items()):
        if name.startswith("odoo.upgrade.util") and getattr(mod, "_validate_model", None) is _original_validate_model:
            mod._validate_model = _patched_validate_model

def migrate(cr, version):
    _allow_dotless_models()
    for module, _load_index in MODULES:
        if util.module_installed(cr, module):
            util.remove_module(cr, module)
"""


@dataclass
class VanillaModule:
    name: str
    classification: str
    location: str
    load_index: int
    submodule: "Optional[str]" = None
    # Submodule's rel_path (Addon.rel_path == the git Submodule's own .path,
    # both keyed the same way in services.git.list_submodules) — the only
    # reliable key to find the actual Submodule object back later, since a
    # submodule's .name is whatever it was created with (an "owner/repo"
    # slug for submodules added via `oops submodules add`, but a bare path
    # for one added directly via `git submodule add`) and cannot be derived
    # from itself by splitting on "/".
    rel_path: str = ""
    # The addon's own directory name (Path(Addon.path).name). Used by
    # `build_strip_plan` to catch a submodule checked out directly at the
    # repo root (no `.third-party` nesting): such an addon has `rel_path ==
    # ""` (its manifest sits at the submodule's own root), so it cannot be
    # matched to its submodule via `rel_path` the way a nested one is — its
    # directory name has to be checked against every submodule's `.path`
    # instead.
    dir_name: str = ""
    # Set by `flag_kb_collisions` when this "addon" is actually a real Odoo
    # module (core or enterprise) that shouldn't be in the project repo at
    # all. It is still removed either way — this only changes the warning
    # and the report, never whether the module is stripped.
    matched_origin: "Optional[str]" = None


@dataclass
class VanillaReport:
    from_version: str
    to_version: str
    modules: "list[VanillaModule]"
    script_path: str
    branch: "Optional[str]" = None
    image: "Optional[str]" = None
    synced_files: "list[str]" = field(default_factory=list)
    orphan_submodules: "list[str]" = field(default_factory=list)
    generated_at: str = ""
    kb_checked: bool = False

    def __post_init__(self):
        if not self.generated_at:
            self.generated_at = datetime.now(UTC).isoformat()


def discover_non_core_addons(repo_path: Path, sub_meta_by_relpath: dict) -> "list[Addon]":
    """Discover and classify every addon at the repo root.

    Thin filter over `oops_engine.addons.discover_addons` — the one discovery
    pipeline shared with `addons list` and `upgrade analyze`. Every addon it
    returns is non-core by construction: Odoo core is never checked into this
    repo.
    """
    return [
        addon
        for addon in discover_addons(
            repo_path,
            sub_meta_by_relpath,
            author=config.manifest.author,
            prefix=config.project.prefix,
            owner=config.github.owner,
            shallow=True,
        )
        if addon.root
    ]


def load_installed_context(
    repo_path: Path, addons: "list[Addon]", from_version: str, kb_modules: "Optional[dict]" = None
) -> "tuple[dict[str, list[str]], list[str]]":
    """Resolve real dependency data for modules `compute_removal_order` needs
    to see but that aren't among the discovered non-core addons — i.e. the
    Odoo core/enterprise/already-installed modules a custom addon depends on.

    Without this, a custom addon whose manifest ``depends`` lists only core
    modules (e.g. ``sale``, ``account`` — never checked into the repo, so
    never in the discovered set) has no in-`installed` dependency at all and
    gets ``load_index=0`` like every other such addon: safe (nothing
    among the removed modules depends on it either), but uninformative, and
    not what the generated script's own comment claims ("position in the
    forward Odoo registry load order").

    Reads `installed_modules.txt` (the project's authoritative "what's
    actually installed in the target database" list — the same file
    `oops refactor`/`oops misc build-kb --installed-only` already rely on)
    and looks up each entry not already a discovered addon in the global
    Odoo KB for `from_version` to get its real `depends`.

    Returns (extra_depends, warnings): `extra_depends` maps each such module
    name to its KB-recorded depends list — merge into `compute_removal_order`'s
    graph, never into the removed-modules list itself. Degrades gracefully
    (returns `({}, [<one warning>])`) when installed_modules.txt is absent,
    same contract as `flag_kb_collisions` for a missing global KB.

    `kb_modules` lets the caller pass in a KB already loaded via
    `load_odoo_kb(from_version)` (as `flag_kb_collisions` also needs) instead
    of loading it again here.
    """
    info = read_installed_modules(repo_path)
    warnings: "list[str]" = []
    file_name = config.project.file_installed_modules

    if info is None:
        warnings.append(
            f"{file_name} not found — load order only reflects dependencies between the discovered "
            f"non-core modules themselves, not their real position in the Odoo registry. Create it "
            "(one module name per line) for a fully-resolved order."
        )
        return {}, warnings

    missing_at_root, extra_at_root = compute_root_drift(repo_path, info.modules)
    if missing_at_root:
        warnings.append(
            f"{file_name} lists module(s) with no addon at the repo root "
            f"(assumed Odoo core/enterprise, not project-owned): {', '.join(missing_at_root)}"
        )
    if extra_at_root:
        warnings.append(
            f"Addon(s) at the repo root not listed in {file_name} (will still be removed): {', '.join(extra_at_root)}"
        )

    discovered_names = {a.technical_name for a in addons}
    if kb_modules is None:
        kb_modules = load_odoo_kb(from_version)
    extra_depends: "dict[str, list[str]]" = {}
    unresolved: "list[str]" = []
    for name in info.modules:
        if name in discovered_names:
            continue
        entry = kb_modules.get(name)
        if entry is None:
            unresolved.append(name)
            continue
        extra_depends[name] = entry.get("depends", [])

    if unresolved:
        warnings.append(
            f"{len(unresolved)} module(s) in {file_name} have no record in the global Odoo KB for "
            f"{from_version!r} — their dependency chain stops there: {', '.join(sorted(unresolved))}"
        )

    return extra_depends, warnings


def compute_removal_order(
    addons: "list[Addon]", extra_depends: "Optional[dict[str, list[str]]]" = None
) -> "list[VanillaModule]":
    """Order addons for safe uninstall: dependents before their dependencies.

    Reuses `oops_engine.load_order.compute_load_order` — the same algorithm
    that reproduces Odoo's own registry load order. `extra_depends` (from
    `load_installed_context`) extends the graph with the real modules a
    discovered addon depends on but that aren't discovered addons themselves
    (core, or already-installed OCA/third-party) — without it, ordering is
    restricted to the tiny subgraph of addons that depend on each other
    directly. Either way, unresolvable deps are silently dropped by
    `compute_load_order`, which is exactly what we want here. Sorting the
    result *descending* by load_index gives the reverse load order: modules
    loaded last (i.e. the most dependent) are removed first.
    """
    installed = {a.technical_name for a in addons}
    depends = {a.technical_name: a.depends for a in addons}
    if extra_depends:
        installed |= set(extra_depends)
        depends.update(extra_depends)

    try:
        order = compute_load_order(installed, depends)
    except RecursionError as exc:
        raise OopsError(
            "Dependency cycle detected among project addons — cannot compute a safe uninstall order."
        ) from exc

    by_name = {a.technical_name: a for a in addons}
    ranked = sorted(
        ((name, load_index) for name, (_depth, load_index) in order.items() if name in by_name),
        key=lambda item: item[1],
        reverse=True,
    )
    return [
        VanillaModule(
            name=name,
            classification=by_name[name].classification or "",
            location=by_name[name].location,
            load_index=load_index,
            submodule=by_name[name].submodule or None,
            rel_path=by_name[name].rel_path,
            dir_name=Path(by_name[name].path).name,
        )
        for name, load_index in ranked
    ]


def flag_kb_collisions(
    modules: "list[VanillaModule]", from_version: str, kb_modules: "Optional[dict]" = None
) -> "tuple[bool, list[str]]":
    """Cross-check every module against the global Odoo KB for `from_version`.

    Any module whose technical name matches a real Odoo core/enterprise
    module (per `services.kb.load_odoo_kb`) is annotated in place
    (`module.matched_origin`) and a warning string is returned for it —
    it is NOT removed from `modules`; the caller still strips it.

    Returns (kb_checked, warnings): `kb_checked` is False if the global KB
    for `from_version` was never built (`load_odoo_kb` returns `{}` in that
    case, per its own documented graceful-degradation contract — this is
    not an error, just a weaker guarantee, surfaced as one extra warning).

    `kb_modules` lets the caller pass in a KB already loaded via
    `load_odoo_kb(from_version)` (as `load_installed_context` also needs)
    instead of loading it again here.
    """
    if kb_modules is None:
        kb_modules = load_odoo_kb(from_version)
    warnings: "list[str]" = []

    if not kb_modules:
        warnings.append(
            f"Global Odoo KB not found for version {from_version!r} — core/enterprise collision "
            f"detection skipped. Run `oops misc build-kb --version {from_version}` first for full detection."
        )
        return False, warnings

    for m in modules:
        entry = kb_modules.get(m.name)
        if entry is None:
            continue
        origin = normalize_origin(entry.get("origin")) or "core"
        m.matched_origin = origin
        warnings.append(
            f"'{m.name}' is classified as {m.classification!r} but matches a real Odoo {origin} "
            "module in the global KB — likely committed by mistake. It will still be removed."
        )

    return True, warnings


def render_uninstall_script(modules: "list[VanillaModule]") -> str:
    lines = "\n".join(f'    ("{m.name}", {m.load_index}),' for m in modules)
    return UNINSTALL_SCRIPT_TEMPLATE.format(
        generated_at=datetime.now(UTC).isoformat(),
        dotless_models=", ".join(f'"{m}"' for m in config.upgrade.dotless_models),
        module_lines=lines,
        script_path=SCRIPT_REL_PATH,
    )


def write_uninstall_script(repo_path: Path, content: str, dry_run: bool = False) -> Path:
    script_path = repo_path / SCRIPT_REL_PATH
    if dry_run:
        return script_path
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(content, encoding="utf-8")
    return script_path


def save_vanilla_report(path: Path, report: VanillaReport) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(asdict(report), sort_keys=False), encoding="utf-8")


# ---------------------------------------------------------------------------
# Git mutation: strip submodules/local addons
# ---------------------------------------------------------------------------


def build_strip_plan(repo: Repo, repo_path: Path, modules: "list[VanillaModule]") -> "tuple[Plan, dict]":
    """One PlanAction per addon: submodule-backed ones remove the submodule
    + its symlinks; root-level ("local") ones remove the addon directory.

    Modeled directly on `commands/submodules/remove.py:_build_plan`, extended
    to cover every addon rather than a user-selected subset, to handle
    root-level (non-submodule) addons, and — beyond what that command does —
    to guarantee every registered submodule is removed, not only the ones
    hosting a discovered addon:

    1. A submodule whose addon lives under a nested path (the common case,
       e.g. `.third-party/<org>/<repo>`) is matched via `rel_path`, exactly
       as before.
    2. A submodule checked out directly at the repo root has no nesting, so
       its addon's `rel_path` is `""` and step 1 cannot match it — it is
       instead matched by comparing the addon's own directory name
       (`dir_name`) against every submodule's `.path`. Without this, such a
       submodule is wrongly treated as a plain local directory: its files
       get `git rm -r`'d but its `.gitmodules`/`.git/config`/
       `.git/modules/<name>` entries are never cleaned up.
    3. After every discovered addon has been matched (or not), any
       remaining registered submodule — one with no discovered addon at
       all: never symlinked ("inactive"), genuinely addon-less, or not
       initialized on disk — gets its own removal action too. Every
       submodule must go, per this command's "full non-core wipe, no
       exceptions" contract; this mirrors the same "no referencing symlink
       → remove" rule `oops submodules prune` already applies on its own,
       generalized here to "no discovered addon at all → remove".

    Submodules are matched by `rel_path` (a Submodule's `.path`, the same key
    `services.git.list_submodules` uses and `Addon.rel_path` already carries)
    rather than by name: a submodule's `.name` is whatever it was created
    with — an "owner/repo" slug for one added via `oops submodules add`, but
    an arbitrary path for one added directly via `git submodule add` — so it
    cannot be reliably derived from itself and must not be used as a lookup key.

    Returns `(plan, sub_by_relpath)` — the caller reuses `sub_by_relpath`
    (a `Submodule.path -> Submodule` mapping) instead of rebuilding it from
    `repo.submodules` a second time.

    4. A submodule's activation symlinks are taken from the discovered addon
       list, not from a filesystem walk: `create_symlink` (io/file.py),
       `addons add` and `addons manage` all place an activation symlink at
       `<repo root>/<addon name>` and nowhere else, so an addon with
       `location == "active"` *is* its own link. `submodules remove` still
       needs the recursive `collect_symlink_paths`/`symlinks_into` pair
       because it removes a subset of submodules and must attribute each link
       to one of them; vanilla removes every submodule, so it has nothing to
       attribute. Not walking also means vanilla never sees a submodule's own
       internal `setup/<addon>/odoo/addons/<addon>` symlinks — tracked by the
       submodule's index, never the superproject's, so a `git rm` on one fails
       with "pathspec did not match any files".
    """
    sub_by_relpath = {s.path: s for s in repo.submodules}
    links_by_relpath: "dict[str, list[Path]]" = {}
    order: "list[str]" = []
    local_modules: "list[VanillaModule]" = []

    for m in modules:
        rel_path = m.rel_path if m.submodule and m.rel_path in sub_by_relpath else None
        if rel_path is None and m.dir_name in sub_by_relpath:
            rel_path = m.dir_name

        if rel_path is None:
            local_modules.append(m)
            continue

        if rel_path not in links_by_relpath:
            links_by_relpath[rel_path] = []
            order.append(rel_path)
        # `location == "active"` means symlinked at the repo root under the
        # addon's own name; the is_symlink() guard keeps a hand-made link
        # whose name differs from the addon directory's from being git rm'd
        # blind (it is then caught by the broken-link sweep instead).
        link = repo_path / m.name
        if m.location == "active" and link.is_symlink():
            links_by_relpath[rel_path].append(link)

    def submodule_action(rel_path: str, label: str, orphan: bool = False) -> PlanAction:
        links = links_by_relpath.get(rel_path, [])
        detail = f"submodule, {len(links)} symlink(s)"
        if orphan:
            detail += " — no discovered addon"
        return PlanAction(
            label=label,
            kind="available",
            detail=detail,
            data={"kind": "submodule", "rel_path": rel_path, "links": [str(lnk) for lnk in links], "orphan": orphan},
        )

    actions = [
        PlanAction(label=m.name, kind="available", detail="local addon directory", data={"kind": "local"})
        for m in local_modules
    ]
    actions += [submodule_action(rel_path, sub_by_relpath[rel_path].name) for rel_path in order]
    actions += [
        submodule_action(str(rel_path), sub.name, orphan=True)
        for rel_path, sub in sub_by_relpath.items()
        if rel_path not in links_by_relpath
    ]

    return Plan(title="Modules to strip", actions=actions), sub_by_relpath


def apply_strip_action(repo: Repo, repo_path: Path, sub_by_relpath: dict, action: PlanAction) -> "tuple[str, bool]":
    if action.data["kind"] == "submodule":
        remove_submodule(
            repo,
            repo_path,
            sub_by_relpath[action.data["rel_path"]],
            [Path(s) for s in action.data["links"]],
        )
    else:
        repo.git.rm("-r", "--force", "--", action.label)
    return "removed", True


def cleanup_submodule_containers(repo_path: Path) -> "list[str]":
    """Remove the submodule container directories left empty once every
    submodule has been stripped — `.third-party` (`config.submodules.current_path`)
    and any legacy container in `config.submodules.old_paths` (e.g. `third-party`).

    `Submodule.remove()` deletes each submodule's own directory but never
    touches its parent: git doesn't track empty directories at all, so a
    container (or an org-level subdirectory within it, e.g.
    `.third-party/OCA`) left with nothing but empty subdirectories after the
    last submodule under it is gone is pure filesystem residue, invisible to
    `git status`. Checked bottom-up, on the actual (live) directory contents
    rather than a precomputed listing, so a subdirectory just emptied by an
    earlier step of this same pass is correctly seen as empty by its parent.

    A container with any real leftover content (a non-submodule file
    committed there) is left untouched — only directories found genuinely
    empty are removed.
    """
    removed: "list[str]" = []
    for rel in [config.submodules.current_path, *config.submodules.old_paths]:
        container = repo_path / rel
        if not container.is_dir():
            continue
        for dirpath, _dirnames, _filenames in os.walk(container, topdown=False):
            p = Path(dirpath)
            if p != container and not any(p.iterdir()):
                p.rmdir()
        if not any(container.iterdir()):
            container.rmdir()
            removed.append(str(rel))
    return removed


def sweep_broken_root_symlinks(repo: Repo, repo_path: Path) -> "list[str]":
    """Drop root-level symlinks left pointing at nothing after the strip.

    Activation symlinks are derived from the discovered addon list, which can
    only see a link whose target still holds a readable manifest. A link that
    was already broken before the run — or one whose name differs from its
    target directory's — yields no addon, so nothing removes it, and
    `repo.git.add("-A")` will not either: a dangling symlink is still a valid
    `120000` blob. Left alone it would be committed into the vanilla base.

    `--ignore-unmatch` keeps an untracked link from raising; it is unlinked
    from disk afterwards either way.
    """
    removed: "list[str]" = []
    for entry in sorted(repo_path.iterdir()):
        if not entry.is_symlink() or entry.exists():
            continue
        repo.git.rm("--force", "--ignore-unmatch", "--", entry.name)
        if entry.is_symlink():
            entry.unlink()
        removed.append(entry.name)
    return removed


# ---------------------------------------------------------------------------
# requirements.txt / packages.txt
# ---------------------------------------------------------------------------


def ensure_upgrade_util_requirement(repo_path: Path, dry_run: bool = False) -> Path:
    """Overwrite requirements.txt with only the upgrade-util pip line.

    Unlike `ensure_git_package` for packages.txt (a user-curated OS-package
    list, unrelated to addons), requirements.txt is addon-derived — and every
    addon is being stripped. Whatever is already there (e.g. a file just
    written by `sync_project_files`) belongs to modules that no longer exist
    in this tree, so it is discarded rather than merged into. Not derived via
    `io/requirements.generate_requirements` either (same reason: it builds its
    output purely from addon manifests, none of which remain). A later
    `oops requirements update` run on this branch will regenerate the file
    from whatever addons exist at that point and will drop this line unless
    re-added — a known limitation, not fixed here.
    """
    req_path = repo_path / config.project.file_requirements
    if dry_run:
        return req_path
    req_path.write_text(f"# generated by `oops upgrade vanilla`\n{UPGRADE_UTIL_REQUIREMENT}\n", encoding="utf-8")
    return req_path


def ensure_git_package(repo_path: Path, dry_run: bool = False) -> Path:
    """Ensure `git` is listed in packages.txt.

    pip's `git+https://...` VCS syntax (used for the upgrade-util
    requirement above) shells out to the system `git` binary at install
    time — if the project's image doesn't install it, `pip install -r
    requirements.txt` fails there. Unlike requirements.txt, packages.txt is
    a user-curated OS-package list, not addon-derived, so this merges "git"
    into whatever is already present rather than overwriting the file.
    """
    packages_path = repo_path / config.project.file_packages
    existing = parse_packages(repo_path) if packages_path.exists() else []
    if "git" in existing or dry_run:
        return packages_path
    write_text_file(packages_path, sorted({*existing, "git"}))
    return packages_path


# ---------------------------------------------------------------------------
# Bump to target version / sync project scaffolding
# ---------------------------------------------------------------------------


def bump_odoo_version(repo_path: Path, to_version: str, dry_run: bool = False) -> str:
    """Write odoo_version.txt to the latest available image for `to_version`.

    Keeps the current edition (community/enterprise) and picks the newest
    release of the target major version — the same image-lookup mechanism
    `oops project update` uses for same-version refreshes
    (`services.docker.find_available_images`), but targeting a different
    (destination) major version instead of the current one.
    """
    try:
        current = parse_odoo_version(repo_path)
    except ValueError as exc:
        raise OopsError(f"Could not read current Odoo version from {config.project.file_odoo_version}.") from exc

    try:
        to_major = float(to_version)
    except ValueError as exc:
        raise OopsError(f"Invalid --to version: {to_version!r} (expected e.g. '19.0').") from exc

    try:
        images = find_available_images(version=to_major, enterprise=current.enterprise, release=None)
    except requests.RequestException as exc:
        raise APIError(f"Failed to fetch available images: {exc}") from exc

    if not images:
        raise OopsError(f"No Odoo image found for version {to_version}.")

    new_image = images[0].image
    if not dry_run:
        write_text_file(repo_path / config.project.file_odoo_version, [new_image])
    return new_image


def sync_project_files(repo_path: Path, dry_run: bool = False) -> "list[str]":
    """Sync project scaffolding from the configured remote (`oops project sync`).

    Degrades gracefully — returns `[]` without error when `sync.remote_url`
    isn't configured, since this is a bonus step inside a much larger
    destructive operation, not vanilla's primary purpose.
    """
    remote_url = config.sync.remote_url
    files = sorted(config.sync.files)
    if not remote_url or not files:
        return []
    if dry_run:
        return files

    with tempfile.TemporaryDirectory() as _tmpdir:
        tmpdir = Path(_tmpdir)
        fetch_project_files(remote_url, config.sync.branch, files, tmpdir)
        return copy_project_files(tmpdir, files, repo_path)


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------


@command(name="vanilla", help=__doc__)
@click.option(
    "--from",
    "from_version",
    default=None,
    help="Source Odoo version (e.g. 18.0). Detected from odoo_version.txt/branch if omitted.",
)
@click.option(
    "--to",
    "to_version",
    default=None,
    help="Target Odoo version (e.g. 19.0). Required — the vanilla base is built on the destination version.",
)
@click.option("--branch", "branch_name", default=None, help="Branch to create (default: vanilla/<to_version>).")
@click.option("--dry-run", is_flag=True, help="Show what would happen, no git changes.")
@click.option("--no-commit", is_flag=True, help="Strip and generate the script, but do not commit.")
@click.option("-f", "--force", is_flag=True, help="Apply without prompting.")
@click.option("--format", "output_format", type=click.Choice(["text", "json"]), default="text", show_default=True)
@click.option("--output-path", type=click.Path(dir_okay=False, path_type=Path), default=None)
@click.pass_context
def main(  # noqa: C901
    ctx, from_version, to_version, branch_name, dry_run, no_commit, force, output_format, output_path
):
    """Strip non-core addons, bump to the target version, and generate an upgrade-util uninstall script."""
    warn_experimental()
    formatter: OutputFormatter = FORMATTERS[output_format]()
    metadata = get_metadata()
    repo, repo_path = require_repository()

    # Resolve from_version — the version modules are discovered/ordered/KB-checked against.
    if not from_version:
        from_version = config.manifest.odoo_version or ""
        if not from_version:
            try:
                from_version = str(parse_odoo_version(repo_path).major_version)
            except (ValueError, OSError):
                from_version = ""
        if not from_version:
            try:
                branch_probe = repo.active_branch.name
            except TypeError:
                branch_probe = ""
            match = re.search(r"\b(\d+\.\d+)\b", branch_probe)
            from_version = match.group(1) if match else ""
    if not from_version:
        raise OopsError(
            "Cannot detect source Odoo version. Provide --from (e.g. --from 18.0), "
            f"set manifest.odoo_version in .oops.yaml, or check {config.project.file_odoo_version}."
        )

    if not to_version:
        raise OopsError("Target version required. Provide --to (e.g. --to 19.0).")

    branch_name = branch_name or f"mig/{to_version}/vanilla"

    # `metadata.parameters` was snapshotted from raw CLI options before this
    # callback resolved from_version/to_version/branch_name — refresh it so
    # presenters see the actual values used, not the CLI defaults (None).
    if metadata is not None:
        metadata.parameters.update({"from_version": from_version, "to_version": to_version, "branch": branch_name})

    sub_meta_by_relpath = list_submodules(repo)

    with live_progress("Discovering non-core addons…"):
        addons = discover_non_core_addons(repo_path, sub_meta_by_relpath)

    if not addons and not sub_meta_by_relpath:
        raise OopsError("No non-core addons found and no submodules registered — nothing to strip.")

    with live_progress(f"Loading the global Odoo KB ({from_version})…"):
        kb_modules = load_odoo_kb(from_version)

    with live_progress(f"Resolving installed-module context ({config.project.file_installed_modules})…"):
        extra_depends, installed_warnings = load_installed_context(
            repo_path, addons, from_version, kb_modules=kb_modules
        )

    with live_progress("Computing safe removal order…"):
        modules = compute_removal_order(addons, extra_depends)

    with live_progress(f"Checking against the global Odoo KB ({from_version})…"):
        kb_checked, kb_warnings = flag_kb_collisions(modules, from_version, kb_modules=kb_modules)

    # Surface warnings now, before the strip plan is even presented — the
    # user must know collision detection was skipped (or what it found),
    # and whether the removal order is fully resolved or restricted to the
    # discovered-addon subgraph, while they can still decide not to proceed —
    # not only in the final summary after everything has already been
    # stripped/committed.
    warning_section(installed_warnings + kb_warnings)

    script_content = render_uninstall_script(modules)

    outer: Result[None] = Result()
    for w in installed_warnings + kb_warnings:
        outer.add_warning(w)

    rows = [[m.name, m.classification, str(m.load_index), m.matched_origin or ""] for m in modules]

    # Read-only (filesystem symlink walk + repo.submodules read) — safe to
    # build before the dry-run branch so --dry-run previews the orphan
    # sweep too, not only the addon-backed removals.
    plan, sub_by_relpath = build_strip_plan(repo, repo_path, modules)
    orphan_submodules = [a.label for a in plan.actionable if a.data.get("orphan")]
    for name in orphan_submodules:
        outer.add_warning(f"Submodule '{name}' has no discovered addon (never symlinked, or empty) — removed anyway.")

    if dry_run:
        with live_progress(f"Checking target image for {to_version}…"):
            preview_image = bump_odoo_version(repo_path, to_version, dry_run=True)
        preview_synced = sync_project_files(repo_path, dry_run=True)

        log.info(f"[dry-run] Would create branch {branch_name!r} from current HEAD.")
        for m in modules:
            flag = f" [{m.matched_origin}!]" if m.matched_origin else ""
            log.info(f"[dry-run] Would remove {m.name} (load_index={m.load_index}){flag}.")
        for name in orphan_submodules:
            log.info(f"[dry-run] Would remove orphan submodule {name!r} (no discovered addon).")
        containers = [config.submodules.current_path, *config.submodules.old_paths]
        log.info(f"[dry-run] Would remove any of {', '.join(str(p) for p in containers)} left empty afterward.")
        log.info(f"[dry-run] Would bump {config.project.file_odoo_version} to {preview_image!r}.")
        if preview_synced:
            log.info(f"[dry-run] Would sync project files: {', '.join(preview_synced)}.")
        else:
            log.info("[dry-run] sync.remote_url not configured — project sync would be skipped.")
        log.info(f"[dry-run] Would write {SCRIPT_REL_PATH}.")
        log.info(f"[dry-run] Would write {config.project.file_requirements} with the upgrade-util requirement.")
        log.info(f"[dry-run] Would ensure 'git' is listed in {config.project.file_packages}.")
        if not no_commit:
            log.info("[dry-run] Would commit.")

        result: "Result[dict]" = Result()
        result.data = {
            "cmd": f"Upgrade vanilla ({from_version} -> {to_version}, dry-run)",
            "dry_run": True,
            "rows": rows,
            "script_path": str(SCRIPT_REL_PATH),
            "branch": None,
            "image": preview_image,
            "synced_files": preview_synced,
            "kb_checked": kb_checked,
            "orphan_submodules": orphan_submodules,
        }
        result.merge(outer)
        output = VanillaPresenter().prepare(result, target=formatter.target, metadata=metadata)
        render_and_exit(result, formatter, output, output_format, output_path)
        return

    # Plan/order/KB-check were all computed above, against the source-version
    # tree exactly as it stood at the start of this run. Nothing has been
    # mutated yet — the branch is not created here either: `on_confirmed`
    # below only runs once the user has actually agreed to proceed (or
    # --force skipped the prompt), never on mere presentation of the plan.
    # `sub_by_relpath` was already computed once by `build_strip_plan` above.

    def apply(action: PlanAction) -> "tuple[str, bool]":
        return apply_strip_action(repo, repo_path, sub_by_relpath, action)

    def create_branch() -> None:
        if branch_name in {h.name for h in repo.heads}:
            raise OopsError(
                f"Branch {branch_name!r} already exists — pass --branch to use a different name, "
                "or delete/rename the existing branch first."
            )
        with live_progress(f"Creating branch {branch_name!r}…"):
            repo.git.checkout("-b", branch_name)

    run_mutation_workflow(
        plan=plan,
        apply=apply,
        outer=outer,
        title="Strip non-core addons",
        force=force,
        select=False,
        on_confirmed=create_branch,
        empty_message="Nothing to strip.",
    )

    if not outer.ok:
        # A per-action strip failure (`outer.add_error`, set by
        # `run_mutation_workflow`) must stop the run here: proceeding to
        # container cleanup, the version bump, project sync, script/
        # requirements writes, and the commit itself would silently bake a
        # partially-stripped tree into a "vanilla" base branch that claims
        # to be a full non-core wipe.
        outer.add_warning(
            f"Strip failed for one or more actions — branch {branch_name!r} left uncommitted for "
            "inspection. Fix the reported error(s) and re-run, or delete the branch and retry."
        )
        result: "Result[dict]" = Result()
        result.data = {
            "cmd": f"Upgrade vanilla ({from_version} -> {to_version})",
            "dry_run": False,
            "rows": rows,
            "script_path": str(SCRIPT_REL_PATH),
            "branch": None,
            "kb_checked": kb_checked,
            "orphan_submodules": orphan_submodules,
        }
        result.merge(outer)
        output = VanillaPresenter().prepare(result, target=formatter.target, metadata=metadata)
        render_and_exit(result, formatter, output, output_format, output_path)
        return

    with live_progress("Sweeping symlinks left broken by the strip…"):
        swept = sweep_broken_root_symlinks(repo, repo_path)
    for name in swept:
        outer.add_warning(f"Removed symlink {name!r}, left broken by the strip.")

    with live_progress("Cleaning up empty submodule container directories…"):
        removed_containers = cleanup_submodule_containers(repo_path)
    for name in removed_containers:
        log.info(f"Removed now-empty submodule container directory {name!r}.")

    with live_progress(f"Bumping to Odoo {to_version}…"):
        new_image = bump_odoo_version(repo_path, to_version)

    with live_progress("Syncing project scaffolding…"):
        synced_files = sync_project_files(repo_path)
    if not synced_files and config.sync.remote_url:
        outer.add_warning("Project sync configured but nothing was synced (no matching files found upstream).")
    elif not config.sync.remote_url:
        outer.add_warning("sync.remote_url not configured — project sync skipped.")

    write_uninstall_script(repo_path, script_content)
    ensure_upgrade_util_requirement(repo_path)
    ensure_git_package(repo_path)
    repo.git.add("-A")

    branch_ref = None
    if not no_commit:
        outer.merge(
            commit_v2(
                repo,
                repo_path,
                [],
                "vanilla_strip",
                from_version=from_version,
                to_version=to_version,
                skip_hooks=True,
                already_staged=True,
            )
        )
        if outer.ok:
            branch_ref = branch_name
    else:
        outer.add_warning("Don't forget to commit to share this vanilla base with the team.")

    report_path = artifact_path(repo_path, VANILLA_REPORT_FILE)
    save_vanilla_report(
        report_path,
        VanillaReport(
            from_version=from_version,
            to_version=to_version,
            modules=modules,
            script_path=str(SCRIPT_REL_PATH),
            branch=branch_ref,
            image=new_image,
            synced_files=synced_files,
            orphan_submodules=orphan_submodules,
            kb_checked=kb_checked,
        ),
    )

    final_result: "Result[dict]" = Result()
    final_result.data = {
        "cmd": f"Upgrade vanilla ({from_version} -> {to_version})",
        "dry_run": False,
        "rows": rows,
        "script_path": str(SCRIPT_REL_PATH),
        "branch": branch_ref,
        "image": new_image,
        "synced_files": synced_files,
        "report_path": str(report_path),
        "kb_checked": kb_checked,
        "orphan_submodules": orphan_submodules,
    }
    final_result.merge(outer)

    output = VanillaPresenter().prepare(final_result, target=formatter.target, metadata=metadata)
    render_and_exit(final_result, formatter, output, output_format, output_path)
