# Copyright 2026 apik (https://apik.cloud).
# License AGPL-3.0-only (https://www.gnu.org/licenses/agpl-3.0.html)

"""
Strip every non-core addon (custom, OCA, third-party) from the project and
replace it with an upgrade-util script that uninstalls the same modules from
the database, in reverse Odoo registry load order, the first time the
migrated database boots.

This is the "vanilla" starting point: a branch/tag stripped down to pure
Odoo core, used as the base for every MdV (montee de version) project.
Independent of state.yml/plan.yml — no per-module porting decisions apply
here, everything non-core is removed.
"""

from __future__ import annotations

import os
import re
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

import click
import yaml
from git import Repo
from oops.commands.base import command, render_and_exit
from oops.core.config import config
from oops.core.exceptions import OopsError
from oops.core.logger import live_progress, log
from oops.core.metadata import get_metadata
from oops.core.models import Plan, PlanAction, Result
from oops.io.file import parse_odoo_version, parse_packages, write_text_file
from oops.output.formatters import FormatterRegistry, JsonFormatter, OutputFormatter, SimpleSummaryConsoleFormatter
from oops.output.workflow import run_mutation_workflow
from oops.services.git import commit_v2, list_submodules, require_repository
from oops.services.kb import load_odoo_kb
from oops.utils.render import warn_experimental
from oops_engine.addons import dedup_addons_by_path, enrich_addon_from_subs
from oops_engine.compat import Optional
from oops_engine.load_order import compute_load_order
from oops_engine.models import Addon
from oops_engine.provenance import normalize_origin

from .common import ARTIFACT_DIR, artifact_path
from .presenters.vanilla import VanillaPresenter

UTC = timezone.utc

FORMATTERS: FormatterRegistry = {
    "text": SimpleSummaryConsoleFormatter,
    "json": JsonFormatter,
}

UPGRADE_UTIL_REQUIREMENT = "odoo_upgrade @ git+https://github.com/odoo/upgrade-util@master"

VANILLA_REPORT_FILE = ARTIFACT_DIR / "vanilla.yml"
SCRIPT_REL_PATH = Path("upgrades") / "base" / "0.0.0" / "end-uninstall_non_core_modules.py"

UNINSTALL_SCRIPT_TEMPLATE = '''\
# Auto-generated by `oops upgrade vanilla` on {generated_at}.
# Do not edit by hand — regenerate with `oops upgrade vanilla`.
#
# Uninstalls every non-core module still present in the database, in
# reverse Odoo registry load order (last-loaded first), to return the
# database to a pure Odoo-standard state. Idempotent: safe to run on every
# boot, becomes a no-op once every listed module is already uninstalled.
#
# See: https://www.odoo.com/documentation/master/developer/reference/upgrades/upgrade_scripts.html

from odoo.upgrade import util

# (module_name, load_index) — load_index is the module's position in the
# forward Odoo registry load order; modules are removed highest-first.
MODULES = [
{module_lines}
]


def migrate(cr, version):
    for module, _load_index in MODULES:
        if util.module_installed(cr, module):
            util.remove_module(cr, module)
'''


@dataclass
class VanillaModule:
    name: str
    classification: str
    location: str
    load_index: int
    submodule: "Optional[str]" = None
    # Submodule's rel_path (Addon.rel_path == the git Submodule's own .path,
    # both keyed the same way in services.git.list_submodules) — the only
    # reliable key to find the actual Submodule object back later, since a
    # submodule's .name is whatever it was created with (an "owner/repo"
    # slug for submodules added via `oops submodules add`, but a bare path
    # for one added directly via `git submodule add`) and cannot be derived
    # from itself by splitting on "/".
    rel_path: str = ""
    # Set by `flag_kb_collisions` when this "addon" is actually a real Odoo
    # module (core or enterprise) that shouldn't be in the project repo at
    # all. It is still removed either way — this only changes the warning
    # and the report, never whether the module is stripped.
    matched_origin: "Optional[str]" = None


@dataclass
class VanillaReport:
    from_version: str
    modules: "list[VanillaModule]"
    script_path: str
    branch: "Optional[str]" = None
    tag: "Optional[str]" = None
    generated_at: str = ""
    kb_checked: bool = False

    def __post_init__(self):
        if not self.generated_at:
            self.generated_at = datetime.now(UTC).isoformat()


def discover_non_core_addons(repo_path: Path, sub_meta_by_relpath: dict) -> "list[Addon]":
    """Discover and classify every addon at the repo root.

    Reuses the exact discovery pattern from `upgrade analyze` (dedup by
    path, then enrich for classification). Every discovered addon is
    non-core by construction — Odoo core is never checked into this repo.
    """
    seen = dedup_addons_by_path(repo_path, shallow=True)
    addons = []
    for addon in seen.values():
        if not addon.root:
            continue
        enrich_addon_from_subs(
            addon,
            sub_meta_by_relpath,
            author=config.manifest.author,
            prefix=config.project.prefix,
            owner=config.github.owner,
        )
        addons.append(addon)
    return addons


def compute_removal_order(addons: "list[Addon]") -> "list[VanillaModule]":
    """Order addons for safe uninstall: dependents before their dependencies.

    Reuses `oops_engine.load_order.compute_load_order` — the same algorithm
    that reproduces Odoo's own registry load order — restricted to the
    project's non-core addons (core/unknown deps are silently dropped by
    that function, which is exactly what we want here). Sorting its output
    *descending* by load_index gives the reverse load order: modules loaded
    last (i.e. the most dependent) are removed first.
    """
    installed = {a.technical_name for a in addons}
    depends = {a.technical_name: a.depends for a in addons}

    try:
        order = compute_load_order(installed, depends)
    except RecursionError as exc:
        raise OopsError(
            "Dependency cycle detected among project addons — cannot compute a safe uninstall order."
        ) from exc

    by_name = {a.technical_name: a for a in addons}
    ranked = sorted(order.items(), key=lambda item: item[1][1], reverse=True)
    return [
        VanillaModule(
            name=name,
            classification=by_name[name].classification or "",
            location=by_name[name].location,
            load_index=load_index,
            submodule=by_name[name].submodule or None,
            rel_path=by_name[name].rel_path,
        )
        for name, (_depth, load_index) in ranked
    ]


def flag_kb_collisions(modules: "list[VanillaModule]", from_version: str) -> "tuple[bool, list[str]]":
    """Cross-check every module against the global Odoo KB for `from_version`.

    Any module whose technical name matches a real Odoo core/enterprise
    module (per `services.kb.load_odoo_kb`) is annotated in place
    (`module.matched_origin`) and a warning string is returned for it —
    it is NOT removed from `modules`; the caller still strips it.

    Returns (kb_checked, warnings): `kb_checked` is False if the global KB
    for `from_version` was never built (`load_odoo_kb` returns `{}` in that
    case, per its own documented graceful-degradation contract — this is
    not an error, just a weaker guarantee, surfaced as one extra warning).
    """
    kb_modules = load_odoo_kb(from_version)
    warnings: "list[str]" = []

    if not kb_modules:
        warnings.append(
            f"Global Odoo KB not found for version {from_version!r} — core/enterprise collision "
            f"detection skipped. Run `oops misc build-kb --version {from_version}` first for full detection."
        )
        return False, warnings

    for m in modules:
        entry = kb_modules.get(m.name)
        if entry is None:
            continue
        origin = normalize_origin(entry.get("origin")) or "core"
        m.matched_origin = origin
        warnings.append(
            f"'{m.name}' is classified as {m.classification!r} but matches a real Odoo {origin} "
            "module in the global KB — likely committed by mistake. It will still be removed."
        )

    return True, warnings


def render_uninstall_script(modules: "list[VanillaModule]") -> str:
    lines = "\n".join(f'    ("{m.name}", {m.load_index}),' for m in modules)
    return UNINSTALL_SCRIPT_TEMPLATE.format(
        generated_at=datetime.now(UTC).isoformat(),
        module_lines=lines,
    )


def write_uninstall_script(repo_path: Path, content: str, dry_run: bool = False) -> Path:
    script_path = repo_path / SCRIPT_REL_PATH
    if dry_run:
        return script_path
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(content, encoding="utf-8")
    return script_path


def save_vanilla_report(path: Path, report: VanillaReport) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(asdict(report), sort_keys=False), encoding="utf-8")


# ---------------------------------------------------------------------------
# Git mutation: strip submodules/local addons
# ---------------------------------------------------------------------------


def _collect_symlinks(repo_path: Path) -> "list[Path]":
    result = []
    for root, dirs, files in os.walk(repo_path):
        if ".git" in dirs:
            dirs.remove(".git")
        for entry in dirs + files:
            p = Path(root) / entry
            if p.is_symlink():
                result.append(p)
    return result


def build_strip_plan(repo: Repo, repo_path: Path, modules: "list[VanillaModule]") -> Plan:
    """One PlanAction per addon: submodule-backed ones remove the submodule
    + its symlinks; root-level ("local") ones remove the addon directory.

    Modeled directly on `commands/submodules/remove.py:_build_plan`, extended
    to cover every addon rather than a user-selected subset, and to handle
    root-level (non-submodule) addons.

    Submodules are matched by `rel_path` (a Submodule's `.path`, the same key
    `services.git.list_submodules` uses and `Addon.rel_path` already carries)
    rather than by name: a submodule's `.name` is whatever it was created
    with — an "owner/repo" slug for one added via `oops submodules add`, but
    an arbitrary path for one added directly via `git submodule add` — so it
    cannot be reliably derived from itself and must not be used as a lookup key.
    """
    all_symlinks = _collect_symlinks(repo_path)
    sub_by_relpath = {s.path: s for s in repo.submodules}
    actions = []
    seen_submodules: "set[str]" = set()

    for m in modules:
        if m.submodule and m.rel_path in sub_by_relpath:
            if m.rel_path in seen_submodules:
                continue
            seen_submodules.add(m.rel_path)
            sub = sub_by_relpath[m.rel_path]
            links = [lnk for lnk in all_symlinks if m.rel_path in os.readlink(lnk)]
            actions.append(
                PlanAction(
                    label=sub.name,
                    kind="available",
                    detail=f"submodule, {len(links)} symlink(s)",
                    data={"kind": "submodule", "rel_path": m.rel_path, "links": [str(lnk) for lnk in links]},
                )
            )
        else:
            actions.append(
                PlanAction(
                    label=m.name,
                    kind="available",
                    detail="local addon directory",
                    data={"kind": "local"},
                )
            )
    return Plan(title="Modules to strip", actions=actions)


def apply_strip_action(
    repo: Repo, repo_path: Path, sub_by_relpath: dict, action: PlanAction
) -> "tuple[str, bool]":
    if action.data["kind"] == "submodule":
        for lnk_str in action.data["links"]:
            rel = os.path.relpath(Path(lnk_str), repo_path)
            repo.git.rm("--force", "--", rel)
        sub_by_relpath[action.data["rel_path"]].remove(force=True)
    else:
        repo.git.rm("-r", "--force", "--", action.label)
    return "removed", True


# ---------------------------------------------------------------------------
# requirements.txt / packages.txt
# ---------------------------------------------------------------------------


def ensure_upgrade_util_requirement(repo_path: Path, dry_run: bool = False) -> Path:
    """Write requirements.txt with the upgrade-util pip line.

    Written directly (not via `io/requirements.generate_requirements`, which
    derives its output purely from addon manifests and would produce nothing
    useful here — every addon is being stripped). A later `oops requirements
    update` run on this branch will regenerate the file from whatever addons
    exist at that point and will drop this line unless re-added — a known
    limitation, not fixed here.
    """
    req_path = repo_path / config.project.file_requirements
    if dry_run:
        return req_path
    req_path.write_text(
        f"# generated by `oops upgrade vanilla`\n{UPGRADE_UTIL_REQUIREMENT}\n",
        encoding="utf-8",
    )
    return req_path


def ensure_git_package(repo_path: Path, dry_run: bool = False) -> Path:
    """Ensure `git` is listed in packages.txt.

    pip's `git+https://...` VCS syntax (used for the upgrade-util
    requirement above) shells out to the system `git` binary at install
    time — if the project's image doesn't install it, `pip install -r
    requirements.txt` fails there. Unlike requirements.txt, packages.txt is
    a user-curated OS-package list, not addon-derived, so this merges "git"
    into whatever is already present rather than overwriting the file.
    """
    packages_path = repo_path / config.project.file_packages
    existing = parse_packages(repo_path) if packages_path.exists() else []
    if "git" in existing or dry_run:
        return packages_path
    write_text_file(packages_path, sorted({*existing, "git"}))
    return packages_path


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------


@command(name="vanilla", help=__doc__)
@click.option(
    "--from",
    "from_version",
    default=None,
    help="Source Odoo version (e.g. 18.0). Detected from odoo_version.txt/branch if omitted.",
)
@click.option("--branch", "branch_name", default=None, help="Branch to create (default: vanilla/<from_version>).")
@click.option("--tag", "tag_name", default=None, help="Tag to create (default: vanilla-<from_version>).")
@click.option("--dry-run", is_flag=True, help="Show what would happen, no git changes.")
@click.option("--no-commit", is_flag=True, help="Strip and generate the script, but do not commit or tag.")
@click.option("-f", "--force", is_flag=True, help="Apply without prompting.")
@click.option("--format", "output_format", type=click.Choice(["text", "json"]), default="text", show_default=True)
@click.option("--output-path", type=click.Path(dir_okay=False, path_type=Path), default=None)
@click.pass_context
def main(ctx, from_version, branch_name, tag_name, dry_run, no_commit, force, output_format, output_path):  # noqa: C901
    """Strip non-core addons and generate an upgrade-util uninstall script."""
    warn_experimental()
    formatter: OutputFormatter = FORMATTERS[output_format]()
    metadata = get_metadata()
    repo, repo_path = require_repository()

    # Resolve from_version.
    if not from_version:
        from_version = config.manifest.odoo_version or ""
        if not from_version:
            try:
                from_version = str(parse_odoo_version(repo_path).major_version)
            except (ValueError, OSError):
                from_version = ""
        if not from_version:
            try:
                branch_probe = repo.active_branch.name
            except TypeError:
                branch_probe = ""
            match = re.search(r"\b(\d+\.\d+)\b", branch_probe)
            from_version = match.group(1) if match else ""
    if not from_version:
        raise OopsError(
            "Cannot detect source Odoo version. Provide --from (e.g. --from 18.0), "
            f"set manifest.odoo_version in .oops.yaml, or check {config.project.file_odoo_version}."
        )

    branch_name = branch_name or f"vanilla/{from_version}"
    tag_name = tag_name or f"vanilla-{from_version}"

    # `metadata.parameters` was snapshotted from raw CLI options before this
    # callback resolved from_version/branch_name/tag_name — refresh it so
    # presenters see the actual values used, not the CLI defaults (None).
    if metadata is not None:
        metadata.parameters.update(
            {"from_version": from_version, "branch": branch_name, "tag": tag_name}
        )

    sub_meta_by_relpath = list_submodules(repo)

    with live_progress("Discovering non-core addons…"):
        addons = discover_non_core_addons(repo_path, sub_meta_by_relpath)

    if not addons:
        raise OopsError("No non-core addons found — nothing to strip.")

    with live_progress("Computing safe removal order…"):
        modules = compute_removal_order(addons)

    with live_progress(f"Checking against the global Odoo KB ({from_version})…"):
        kb_checked, kb_warnings = flag_kb_collisions(modules, from_version)

    script_content = render_uninstall_script(modules)

    outer: Result[None] = Result()
    for w in kb_warnings:
        outer.add_warning(w)

    rows = [[m.name, m.classification, str(m.load_index), m.matched_origin or ""] for m in modules]

    if dry_run:
        log.info(f"[dry-run] Would create branch {branch_name!r} from current HEAD.")
        for m in modules:
            flag = f" [{m.matched_origin}!]" if m.matched_origin else ""
            log.info(f"[dry-run] Would remove {m.name} (load_index={m.load_index}){flag}.")
        log.info(f"[dry-run] Would write {SCRIPT_REL_PATH}.")
        log.info(f"[dry-run] Would write {config.project.file_requirements} with the upgrade-util requirement.")
        log.info(f"[dry-run] Would ensure 'git' is listed in {config.project.file_packages}.")
        if not no_commit:
            log.info(f"[dry-run] Would commit and tag {tag_name!r}.")

        result: "Result[dict]" = Result()
        result.data = {
            "cmd": f"Upgrade vanilla ({from_version}, dry-run)",
            "dry_run": True,
            "rows": rows,
            "script_path": str(SCRIPT_REL_PATH),
            "branch": None,
            "tag": None,
            "kb_checked": kb_checked,
        }
        result.merge(outer)
        output = VanillaPresenter().prepare(result, target=formatter.target, metadata=metadata)
        render_and_exit(result, formatter, output, output_format, output_path)
        return

    with live_progress(f"Creating branch {branch_name!r}…"):
        repo.git.checkout("-b", branch_name)

    plan = build_strip_plan(repo, repo_path, modules)
    sub_by_relpath = {s.path: s for s in repo.submodules}

    def apply(action: PlanAction) -> "tuple[str, bool]":
        return apply_strip_action(repo, repo_path, sub_by_relpath, action)

    run_mutation_workflow(
        plan=plan,
        apply=apply,
        outer=outer,
        title="Strip non-core addons",
        force=force,
        select=False,
        empty_message="Nothing to strip.",
    )

    write_uninstall_script(repo_path, script_content)
    ensure_upgrade_util_requirement(repo_path)
    ensure_git_package(repo_path)
    repo.git.add("-A")

    branch_ref = None
    tag_ref = None
    if not no_commit:
        outer.merge(
            commit_v2(
                repo,
                repo_path,
                [],
                "vanilla_strip",
                from_version=from_version,
                skip_hooks=True,
                already_staged=True,
            )
        )
        if outer.ok:
            repo.create_tag(tag_name)
            branch_ref, tag_ref = branch_name, tag_name
    else:
        outer.add_warning("Don't forget to commit and tag to share this vanilla base with the team.")

    report_path = artifact_path(repo_path, VANILLA_REPORT_FILE)
    save_vanilla_report(
        report_path,
        VanillaReport(
            from_version=from_version,
            modules=modules,
            script_path=str(SCRIPT_REL_PATH),
            branch=branch_ref,
            tag=tag_ref,
            kb_checked=kb_checked,
        ),
    )

    final_result: "Result[dict]" = Result()
    final_result.data = {
        "cmd": f"Upgrade vanilla ({from_version})",
        "dry_run": False,
        "rows": rows,
        "script_path": str(SCRIPT_REL_PATH),
        "branch": branch_ref,
        "tag": tag_ref,
        "report_path": str(report_path),
        "kb_checked": kb_checked,
    }
    final_result.merge(outer)

    output = VanillaPresenter().prepare(final_result, target=formatter.target, metadata=metadata)
    render_and_exit(final_result, formatter, output, output_format, output_path)
